language: clojure
notifications:
  slack: orionsbelt-game:QT4unoZGVBOvbSWiil1o1bm0
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
services:
  - mongodb
after_script:
  - bash -ex script/coveralls.sh
